### ISSUE TITLE
公众号, 使用redis存储accessToken, 过期后不会自动更新redis.

### ISSUE THREAD

**Issue by bddiudiu** [Wechat-Group/WxJava#3098]
### 简要描述
使用 wx-java-mp-spring-boot-starter, 使用redis作为accessToken的存储. 当accessToken过期后, redis里面没有生成新的accessToken.

### 模块版本情况
* WxJava 模块名:  wx-java-mp-spring-boot-starter
* WxJava 版本号:  4.5.0

### 详细描述
pom中引入
```
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>wx-java-mp-spring-boot-starter</artifactId>
            <version>4.5.0</version>
        </dependency>
```

application.yml中配置了redis和wx.mp
```
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    timeout: 5000

wx:
  mp:
    app-id: 111
    secret: 111
    token: 111
#    aes-key:
    config-storage:
      type: RedisTemplate
      key-prefix: wx
```

首次启动后, redis中会生成accessToken, 但是使用api, 强制过期accessToken, redis中的key会被删除, 但是再次请求也无法获取新的accessToken.

项目内的配置都是根据文档来配置的.
